In [1]:
#Loading packages 
import pandas as pd
import statsmodels.formula.api as smf

In [16]:
#Reading file and viewing data
filename = '/Users/alexu/OneDrive/Documents/MSBA/Capstone/Capstone Predictive Analytics/US Salary Survey Data Round 1.csv'
salaryData = pd.read_csv(filename)
salaryData.head()

,Date,Age_group,Industry,Salary,State,Col_State,Years_proexp,Years_fieldexp,Edu_level,Gender,Race
0,4/27/2021,25_34,Other_Industry,55000.0,Massachusetts,129.9,5_7_years,5_7_years,Masters_degree,Woman,White
1,4/27/2021,25_34,Other_Industry,34000.0,Other_State,89.7,2_4_years,2_4_years,College_degree,Woman,White
2,4/27/2021,25_34,Other_Industry,65000.0,Other_State,96.1,8_10_years,5_7_years,College_degree,Woman,White
3,4/27/2021,25_34,Other_Industry,67000.0,Other_State,95.9,8_10_years,5_7_years,College_degree,Woman,White
4,4/27/2021,25_34,Other_Industry,62000.0,Other_State,108.4,8_10_years,2_4_years,Masters_degree,Man,White

In [3]:
#Checking data types
salaryData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19643 entries, 0 to 19642
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            19643 non-null  object
 1   Age_group       19643 non-null  object
 2   Industry        19643 non-null  object
 3   Salary          19643 non-null  float64
 4   State           19643 non-null  object
 5   Col_State       19643 non-null  float64
 6   Years_proexp    19643 non-null  object
 7   Years_fieldexp  19643 non-null  object
 8   Edu_level       19643 non-null  object
 9   Gender          19643 non-null  object
 10  Race            19643 non-null  object
dtypes: float64(2), object(9)
memory usage: 1.6+ MB

In [4]:
#Creating dummy variables for Age_group
salaryData_with_dummies = pd.get_dummies(data=salaryData, columns=['Age_group'])

In [5]:
print(salaryData_with_dummies)

            Date        Industry   Salary          State  Col_State  \
0      4/27/2021  Other_Industry  55000.0  Massachusetts      129.9
1      4/27/2021  Other_Industry  34000.0    Other_State       89.7
2      4/27/2021  Other_Industry  65000.0    Other_State       96.1
3      4/27/2021  Other_Industry  67000.0    Other_State       95.9
4      4/27/2021  Other_Industry  62000.0    Other_State      108.4
...          ...             ...      ...            ...        ...
19638  4/28/2021  Computing_Tech      0.0     California      142.4
19639  4/28/2021  Other_Industry      0.0     California      142.4
19640  4/29/2021  Computing_Tech      0.0     California      142.4
19641  4/29/2021  Other_Industry      0.0    Other_State      133.7
19642   5/1/2021  Other_Industry      0.0    Other_State      127.2

      Years_proexp Years_fieldexp       Edu_level Gender                 Race  \
0        5_7_years      5_7_years  Masters_degree  Woman                White
1        2_4_years      2_4_years  College_degree  Woman                White
2       8_10_years      5_7_years  College_degree  Woman                White
3       8_10_years      5_7_years  College_degree  Woman                White
4       8_10_years      2_4_years  Masters_degree    Man                White
...            ...            ...             ...    ...                  ...
19638  1_year_less    1_year_less  College_degree    Man  Asian_AsianAmerican
19639    5_7_years      5_7_years             PhD    Man                White
19640  21_30_years    21_30_years    Some_college  Woman                White
19641  21_30_years      5_7_years  Masters_degree    Man                White
19642   8_10_years      2_4_years  Masters_degree  Woman                White

       Age_group_18_24  Age_group_25_34  Age_group_35_44  Age_group_45_54  \
0                    0                1                0                0
1                    0                1                0                0
2                    0                1                0                0
3                    0                1                0                0
4                    0                1                0                0
...                ...              ...              ...              ...
19638                1                0                0                0
19639                0                0                0                1
19640                0                0                0                1
19641                0                0                1                0
19642                0                1                0                0

       Age_group_55_64  Age_group_65_over  Age_group_under_18
0                    0                  0                   0
1                    0                  0                   0
2                    0                  0                   0
3                    0                  0                   0
4                    0                  0                   0
...                ...                ...                 ...
19638                0                  0                   0
19639                0                  0                   0
19640                0                  0                   0
19641                0                  0                   0
19642                0                  0                   0

[19643 rows x 17 columns]

In [6]:
#Regression expression excluding Age_group_under_18 as the intercept
reg_exp = 'Salary ~ Age_group_18_24 + Age_group_25_34 + Age_group_35_44 + Age_group_45_54 + Age_group_55_64 + Age_group_65_over'

In [7]:
#Building and training the model before printing the results
olsr_model = smf.ols(formula=reg_exp, data=salaryData_with_dummies)
olsr_model_results = olsr_model.fit()
print(olsr_model_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.036
Model:                            OLS   Adj. R-squared:                  0.036
Method:                 Least Squares   F-statistic:                     123.5
Date:                Mon, 21 Nov 2022   Prob (F-statistic):          6.64e-154
Time:                        20:30:20   Log-Likelihood:            -2.3585e+05
No. Observations:               19643   AIC:                         4.717e+05
Df Residuals:                   19636   BIC:                         4.718e+05
Df Model:                           6
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept          6.613e+04    1.5e+04      4.412      0.000    3.68e+04    9.55e+04
Age_group_18_24   -3679.7203   1.51e+04     -0.244      0.807   -3.32e+04    2.58e+04
Age_group_25_34    1.567e+04    1.5e+04      1.045      0.296   -1.37e+04    4.51e+04
Age_group_35_44    2.744e+04    1.5e+04      1.830      0.067   -1954.015    5.68e+04
Age_group_45_54    2.877e+04    1.5e+04      1.916      0.055    -655.905    5.82e+04
Age_group_55_64    2.415e+04   1.51e+04      1.604      0.109   -5370.442    5.37e+04
Age_group_65_over  2.721e+04   1.57e+04      1.737      0.082   -3490.995    5.79e+04
==============================================================================
Omnibus:                     1753.117   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2259.273
Skew:                           0.823   Prob(JB):                         0.00
Kurtosis:                       3.227   Cond. No.                         164.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [8]:
#Creating dummy variables for Industry
salaryData_with_dummies = pd.get_dummies(data=salaryData, columns=['Industry'])

In [9]:
print(salaryData_with_dummies)

            Date Age_group   Salary          State  Col_State Years_proexp  \
0      4/27/2021     25_34  55000.0  Massachusetts      129.9    5_7_years
1      4/27/2021     25_34  34000.0    Other_State       89.7    2_4_years
2      4/27/2021     25_34  65000.0    Other_State       96.1   8_10_years
3      4/27/2021     25_34  67000.0    Other_State       95.9   8_10_years
4      4/27/2021     25_34  62000.0    Other_State      108.4   8_10_years
...          ...       ...      ...            ...        ...          ...
19638  4/28/2021     18_24      0.0     California      142.4  1_year_less
19639  4/28/2021     45_54      0.0     California      142.4    5_7_years
19640  4/29/2021     45_54      0.0     California      142.4  21_30_years
19641  4/29/2021     35_44      0.0    Other_State      133.7  21_30_years
19642   5/1/2021     25_34      0.0    Other_State      127.2   8_10_years

      Years_fieldexp       Edu_level Gender                 Race  \
0          5_7_years  Masters_degree  Woman                White
1          2_4_years  College_degree  Woman                White
2          5_7_years  College_degree  Woman                White
3          5_7_years  College_degree  Woman                White
4          2_4_years  Masters_degree    Man                White
...              ...             ...    ...                  ...
19638    1_year_less  College_degree    Man  Asian_AsianAmerican
19639      5_7_years             PhD    Man                White
19640    21_30_years    Some_college  Woman                White
19641      5_7_years  Masters_degree    Man                White
19642      2_4_years  Masters_degree  Woman                White

       Industry_Biotechnology_Pharmaceuticals_MedicalDevices  \
0                                                      0
1                                                      0
2                                                      0
3                                                      0
4                                                      0
...                                                  ...
19638                                                  0
19639                                                  0
19640                                                  0
19641                                                  0
19642                                                  0

       Industry_Computing_Tech  Industry_Energy_Oil_Gas  \
0                            0                        0
1                            0                        0
2                            0                        0
3                            0                        0
4                            0                        0
...                        ...                      ...
19638                        1                        0
19639                        0                        0
19640                        1                        0
19641                        0                        0
19642                        0                        0

       Industry_Engineering_Manufacturing  Industry_Law  \
0                                       0             0
1                                       0             0
2                                       0             0
3                                       0             0
4                                       0             0
...                                   ...           ...
19638                                   0             0
19639                                   0             0
19640                                   0             0
19641                                   0             0
19642                                   0             0

       Industry_Other_Industry
0                            1
1                            1
2                            1
3                            1
4                            1
...                        ...
19638                        0
19639                        1
19640                        0
19641                        1
19642                        1

[19643 rows x 16 columns]

In [10]:
#Regression expression excluding Other_Industry as the intercept
reg_exp = 'Salary ~ Industry_Biotechnology_Pharmaceuticals_MedicalDevices + Industry_Computing_Tech + Industry_Energy_Oil_Gas + Industry_Engineering_Manufacturing + Industry_Law'

In [11]:
#Building and training the model before printing the results
olsr_model = smf.ols(formula=reg_exp, data=salaryData_with_dummies)
olsr_model_results = olsr_model.fit()
print(olsr_model_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.137
Model:                            OLS   Adj. R-squared:                  0.137
Method:                 Least Squares   F-statistic:                     623.3
Date:                Mon, 21 Nov 2022   Prob (F-statistic):               0.00
Time:                        20:38:52   Log-Likelihood:            -2.3477e+05
No. Observations:               19643   AIC:                         4.695e+05
Df Residuals:                   19637   BIC:                         4.696e+05
Df Model:                           5
Covariance Type:            nonrobust
=========================================================================================================================
                                                            coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------------
Intercept                                              7.877e+04    310.572    253.616      0.000    7.82e+04    7.94e+04
Industry_Biotechnology_Pharmaceuticals_MedicalDevices  3.744e+04   2791.470     13.413      0.000     3.2e+04    4.29e+04
Industry_Computing_Tech                                4.074e+04    773.305     52.680      0.000    3.92e+04    4.23e+04
Industry_Energy_Oil_Gas                                2.234e+04   5370.112      4.160      0.000    1.18e+04    3.29e+04
Industry_Engineering_Manufacturing                     2.041e+04   1100.696     18.540      0.000    1.82e+04    2.26e+04
Industry_Law                                           1.859e+04   1414.989     13.139      0.000    1.58e+04    2.14e+04
==============================================================================
Omnibus:                     1728.171   Durbin-Watson:                   1.945
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2219.566
Skew:                           0.791   Prob(JB):                         0.00
Kurtosis:                       3.455   Cond. No.                         20.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [17]:
#Creating dummy variables for State
salaryData_with_dummies = pd.get_dummies(data=salaryData, columns=['State'])

In [18]:
print(salaryData_with_dummies)

            Date Age_group        Industry   Salary  Col_State Years_proexp  \
0      4/27/2021     25_34  Other_Industry  55000.0      129.9    5_7_years
1      4/27/2021     25_34  Other_Industry  34000.0       89.7    2_4_years
2      4/27/2021     25_34  Other_Industry  65000.0       96.1   8_10_years
3      4/27/2021     25_34  Other_Industry  67000.0       95.9   8_10_years
4      4/27/2021     25_34  Other_Industry  62000.0      108.4   8_10_years
...          ...       ...             ...      ...        ...          ...
19638  4/28/2021     18_24  Computing_Tech      0.0      142.4  1_year_less
19639  4/28/2021     45_54  Other_Industry      0.0      142.4    5_7_years
19640  4/29/2021     45_54  Computing_Tech      0.0      142.4  21_30_years
19641  4/29/2021     35_44  Other_Industry      0.0      133.7  21_30_years
19642   5/1/2021     25_34  Other_Industry      0.0      127.2   8_10_years

      Years_fieldexp       Edu_level Gender                 Race  \
0          5_7_years  Masters_degree  Woman                White
1          2_4_years  College_degree  Woman                White
2          5_7_years  College_degree  Woman                White
3          5_7_years  College_degree  Woman                White
4          2_4_years  Masters_degree    Man                White
...              ...             ...    ...                  ...
19638    1_year_less  College_degree    Man  Asian_AsianAmerican
19639      5_7_years             PhD    Man                White
19640    21_30_years    Some_college  Woman                White
19641      5_7_years  Masters_degree    Man                White
19642      2_4_years  Masters_degree  Woman                White

       State_California  State_Massachusetts  State_NewYork  \
0                     0                    1              0
1                     0                    0              0
2                     0                    0              0
3                     0                    0              0
4                     0                    0              0
...                 ...                  ...            ...
19638                 1                    0              0
19639                 1                    0              0
19640                 1                    0              0
19641                 0                    0              0
19642                 0                    0              0

       State_Other_State  State_Virginia  State_Washington
0                      0               0                 0
1                      1               0                 0
2                      1               0                 0
3                      1               0                 0
4                      1               0                 0
...                  ...             ...               ...
19638                  0               0                 0
19639                  0               0                 0
19640                  0               0                 0
19641                  1               0                 0
19642                  1               0                 0

[19643 rows x 16 columns]

In [19]:
#Regression expression excluding Other_State as the intercept
reg_exp = 'Salary ~ State_California + State_Massachusetts + State_NewYork + State_Virginia + State_Washington'

In [20]:
#Building and training the model before printing the results
olsr_model = smf.ols(formula=reg_exp, data=salaryData_with_dummies)
olsr_model_results = olsr_model.fit()
print(olsr_model_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.049
Model:                            OLS   Adj. R-squared:                  0.049
Method:                 Least Squares   F-statistic:                     201.3
Date:                Mon, 21 Nov 2022   Prob (F-statistic):          6.36e-210
Time:                        20:48:50   Log-Likelihood:            -2.3572e+05
No. Observations:               19643   AIC:                         4.715e+05
Df Residuals:                   19637   BIC:                         4.715e+05
Df Model:                           5
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept            8.025e+04    361.841    221.793      0.000    7.95e+04     8.1e+04
State_California     2.453e+04    937.370     26.166      0.000    2.27e+04    2.64e+04
State_Massachusetts  1.442e+04   1138.174     12.673      0.000    1.22e+04    1.67e+04
State_NewYork         1.38e+04    991.886     13.911      0.000    1.19e+04    1.57e+04
State_Virginia       8028.5037   1570.098      5.113      0.000    4950.979    1.11e+04
State_Washington     1.692e+04    975.165     17.350      0.000     1.5e+04    1.88e+04
==============================================================================
Omnibus:                     1727.348   Durbin-Watson:                   1.937
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2217.312
Skew:                           0.814   Prob(JB):                         0.00
Kurtosis:                       3.236   Cond. No.                         5.78
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [23]:
#Regression expression for cost of living index
reg_exp = 'Salary ~ Col_State'

In [24]:
#Building and training the model before printing the results
olsr_model = smf.ols(formula=reg_exp, data=salaryData)
olsr_model_results = olsr_model.fit()
print(olsr_model_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.036
Model:                            OLS   Adj. R-squared:                  0.035
Method:                 Least Squares   F-statistic:                     723.8
Date:                Mon, 21 Nov 2022   Prob (F-statistic):          1.35e-156
Time:                        20:54:15   Log-Likelihood:            -2.3586e+05
No. Observations:               19643   AIC:                         4.717e+05
Df Residuals:                   19641   BIC:                         4.717e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    4.86e+04   1455.468     33.388      0.000    4.57e+04    5.14e+04
Col_State    335.3368     12.464     26.904      0.000     310.906     359.768
==============================================================================
Omnibus:                     1785.451   Durbin-Watson:                   1.931
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2311.242
Skew:                           0.832   Prob(JB):                         0.00
Kurtosis:                       3.232   Cond. No.                         601.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [25]:
#Creating dummy variables for Years_proexp
salaryData_with_dummies = pd.get_dummies(data=salaryData, columns=['Years_proexp'])

In [26]:
print(salaryData_with_dummies)

            Date Age_group        Industry   Salary          State  Col_State  \
0      4/27/2021     25_34  Other_Industry  55000.0  Massachusetts      129.9
1      4/27/2021     25_34  Other_Industry  34000.0    Other_State       89.7
2      4/27/2021     25_34  Other_Industry  65000.0    Other_State       96.1
3      4/27/2021     25_34  Other_Industry  67000.0    Other_State       95.9
4      4/27/2021     25_34  Other_Industry  62000.0    Other_State      108.4
...          ...       ...             ...      ...            ...        ...
19638  4/28/2021     18_24  Computing_Tech      0.0     California      142.4
19639  4/28/2021     45_54  Other_Industry      0.0     California      142.4
19640  4/29/2021     45_54  Computing_Tech      0.0     California      142.4
19641  4/29/2021     35_44  Other_Industry      0.0    Other_State      133.7
19642   5/1/2021     25_34  Other_Industry      0.0    Other_State      127.2

      Years_fieldexp       Edu_level Gender                 Race  \
0          5_7_years  Masters_degree  Woman                White
1          2_4_years  College_degree  Woman                White
2          5_7_years  College_degree  Woman                White
3          5_7_years  College_degree  Woman                White
4          2_4_years  Masters_degree    Man                White
...              ...             ...    ...                  ...
19638    1_year_less  College_degree    Man  Asian_AsianAmerican
19639      5_7_years             PhD    Man                White
19640    21_30_years    Some_college  Woman                White
19641      5_7_years  Masters_degree    Man                White
19642      2_4_years  Masters_degree  Woman                White

       Years_proexp_11_20_years  Years_proexp_1_year_less  \
0                             0                         0
1                             0                         0
2                             0                         0
3                             0                         0
4                             0                         0
...                         ...                       ...
19638                         0                         1
19639                         0                         0
19640                         0                         0
19641                         0                         0
19642                         0                         0

       Years_proexp_21_30_years  Years_proexp_2_4_years  \
0                             0                       0
1                             0                       1
2                             0                       0
3                             0                       0
4                             0                       0
...                         ...                     ...
19638                         0                       0
19639                         0                       0
19640                         1                       0
19641                         1                       0
19642                         0                       0

       Years_proexp_31_40_years  Years_proexp_41_years_more  \
0                             0                           0
1                             0                           0
2                             0                           0
3                             0                           0
4                             0                           0
...                         ...                         ...
19638                         0                           0
19639                         0                           0
19640                         0                           0
19641                         0                           0
19642                         0                           0

       Years_proexp_5_7_years  Years_proexp_8_10_years
0                           1                        0
1                           0                        0
2                           0                        1
3                           0                        1
4                           0                        1
...                       ...                      ...
19638                       0                        0
19639                       1                        0
19640                       0                        0
19641                       0                        0
19642                       0                        1

[19643 rows x 18 columns]

In [27]:
#Regression expression excluding Years_proexp_1_year_less as the intercept
reg_exp = 'Salary ~ Years_proexp_2_4_years + Years_proexp_5_7_years + Years_proexp_8_10_years + Years_proexp_11_20_years + Years_proexp_21_30_years + Years_proexp_31_40_years + Years_proexp_41_years_more'

In [28]:
#Building and training the model before printing the results
olsr_model = smf.ols(formula=reg_exp, data=salaryData_with_dummies)
olsr_model_results = olsr_model.fit()
print(olsr_model_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.048
Model:                            OLS   Adj. R-squared:                  0.047
Method:                 Least Squares   F-statistic:                     140.3
Date:                Mon, 21 Nov 2022   Prob (F-statistic):          1.12e-202
Time:                        21:03:42   Log-Likelihood:            -2.3573e+05
No. Observations:               19643   AIC:                         4.715e+05
Df Residuals:                   19635   BIC:                         4.715e+05
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                   6.894e+04   2197.021     31.380      0.000    6.46e+04    7.32e+04
Years_proexp_2_4_years      2040.9326   2360.583      0.865      0.387   -2586.010    6667.875
Years_proexp_5_7_years      8840.8681   2297.461      3.848      0.000    4337.649    1.33e+04
Years_proexp_8_10_years     1.703e+04   2288.025      7.442      0.000    1.25e+04    2.15e+04
Years_proexp_11_20_years    2.455e+04   2248.557     10.919      0.000    2.01e+04     2.9e+04
Years_proexp_21_30_years    2.838e+04   2333.906     12.161      0.000    2.38e+04     3.3e+04
Years_proexp_31_40_years    2.532e+04   2719.546      9.310      0.000       2e+04    3.06e+04
Years_proexp_41_years_more  2.552e+04   4700.689      5.429      0.000    1.63e+04    3.47e+04
==============================================================================
Omnibus:                     1712.049   Durbin-Watson:                   1.932
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2192.782
Skew:                           0.810   Prob(JB):                         0.00
Kurtosis:                       3.238   Cond. No.                         25.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [29]:
#Creating dummy variables for Years_fieldexp
salaryData_with_dummies = pd.get_dummies(data=salaryData, columns=['Years_fieldexp'])

In [30]:
print(salaryData_with_dummies)

            Date Age_group        Industry   Salary          State  Col_State  \
0      4/27/2021     25_34  Other_Industry  55000.0  Massachusetts      129.9
1      4/27/2021     25_34  Other_Industry  34000.0    Other_State       89.7
2      4/27/2021     25_34  Other_Industry  65000.0    Other_State       96.1
3      4/27/2021     25_34  Other_Industry  67000.0    Other_State       95.9
4      4/27/2021     25_34  Other_Industry  62000.0    Other_State      108.4
...          ...       ...             ...      ...            ...        ...
19638  4/28/2021     18_24  Computing_Tech      0.0     California      142.4
19639  4/28/2021     45_54  Other_Industry      0.0     California      142.4
19640  4/29/2021     45_54  Computing_Tech      0.0     California      142.4
19641  4/29/2021     35_44  Other_Industry      0.0    Other_State      133.7
19642   5/1/2021     25_34  Other_Industry      0.0    Other_State      127.2

      Years_proexp       Edu_level Gender                 Race  \
0        5_7_years  Masters_degree  Woman                White
1        2_4_years  College_degree  Woman                White
2       8_10_years  College_degree  Woman                White
3       8_10_years  College_degree  Woman                White
4       8_10_years  Masters_degree    Man                White
...            ...             ...    ...                  ...
19638  1_year_less  College_degree    Man  Asian_AsianAmerican
19639    5_7_years             PhD    Man                White
19640  21_30_years    Some_college  Woman                White
19641  21_30_years  Masters_degree    Man                White
19642   8_10_years  Masters_degree  Woman                White

       Years_fieldexp_11_20_years  Years_fieldexp_1_year_less  \
0                               0                           0
1                               0                           0
2                               0                           0
3                               0                           0
4                               0                           0
...                           ...                         ...
19638                           0                           1
19639                           0                           0
19640                           0                           0
19641                           0                           0
19642                           0                           0

       Years_fieldexp_21_30_years  Years_fieldexp_2_4_years  \
0                               0                         0
1                               0                         1
2                               0                         0
3                               0                         0
4                               0                         1
...                           ...                       ...
19638                           0                         0
19639                           0                         0
19640                           1                         0
19641                           0                         0
19642                           0                         1

       Years_fieldexp_31_40_years  Years_fieldexp_41_years_more  \
0                               0                             0
1                               0                             0
2                               0                             0
3                               0                             0
4                               0                             0
...                           ...                           ...
19638                           0                             0
19639                           0                             0
19640                           0                             0
19641                           0                             0
19642                           0                             0

       Years_fieldexp_5_7_years  Years_fieldexp_8_10_years
0                             1                          0
1                             0                          0
2                             1                          0
3                             1                          0
4                             0                          0
...                         ...                        ...
19638                         0                          0
19639                         1                          0
19640                         0                          0
19641                         1                          0
19642                         0                          0

[19643 rows x 18 columns]

In [31]:
#Regression expression excluding Years_fieldexp_1_year_less as the intercept
reg_exp = 'Salary ~ Years_fieldexp_2_4_years + Years_fieldexp_5_7_years + Years_fieldexp_8_10_years + Years_fieldexp_11_20_years + Years_fieldexp_21_30_years + Years_fieldexp_31_40_years + Years_fieldexp_41_years_more'

In [32]:
#Building and training the model before printing the results
olsr_model = smf.ols(formula=reg_exp, data=salaryData_with_dummies)
olsr_model_results = olsr_model.fit()
print(olsr_model_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.085
Model:                            OLS   Adj. R-squared:                  0.085
Method:                 Least Squares   F-statistic:                     260.6
Date:                Mon, 21 Nov 2022   Prob (F-statistic):               0.00
Time:                        21:12:55   Log-Likelihood:            -2.3534e+05
No. Observations:               19643   AIC:                         4.707e+05
Df Residuals:                   19635   BIC:                         4.708e+05
Df Model:                           7
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                     6.527e+04   1253.740     52.057      0.000    6.28e+04    6.77e+04
Years_fieldexp_2_4_years      7769.1718   1383.066      5.617      0.000    5058.245    1.05e+04
Years_fieldexp_5_7_years      1.726e+04   1374.571     12.556      0.000    1.46e+04       2e+04
Years_fieldexp_8_10_years     2.679e+04   1410.767     18.991      0.000     2.4e+04    2.96e+04
Years_fieldexp_11_20_years     3.43e+04   1378.845     24.879      0.000    3.16e+04     3.7e+04
Years_fieldexp_21_30_years    4.088e+04   1672.382     24.447      0.000    3.76e+04    4.42e+04
Years_fieldexp_31_40_years    3.793e+04   2696.548     14.067      0.000    3.26e+04    4.32e+04
Years_fieldexp_41_years_more  3.312e+04   7409.653      4.470      0.000    1.86e+04    4.76e+04
==============================================================================
Omnibus:                     1722.135   Durbin-Watson:                   1.932
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2205.541
Skew:                           0.805   Prob(JB):                         0.00
Kurtosis:                       3.315   Cond. No.                         29.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [49]:
#Creating dummy variables for Edu_level
salaryData_with_dummies = pd.get_dummies(data=salaryData, columns=['Edu_level'])

In [50]:
print(salaryData_with_dummies)

            Date Age_group        Industry   Salary          State  Col_State  \
0      4/27/2021     25_34  Other_Industry  55000.0  Massachusetts      129.9
1      4/27/2021     25_34  Other_Industry  34000.0    Other_State       89.7
2      4/27/2021     25_34  Other_Industry  65000.0    Other_State       96.1
3      4/27/2021     25_34  Other_Industry  67000.0    Other_State       95.9
4      4/27/2021     25_34  Other_Industry  62000.0    Other_State      108.4
...          ...       ...             ...      ...            ...        ...
19638  4/28/2021     18_24  Computing_Tech      0.0     California      142.4
19639  4/28/2021     45_54  Other_Industry      0.0     California      142.4
19640  4/29/2021     45_54  Computing_Tech      0.0     California      142.4
19641  4/29/2021     35_44  Other_Industry      0.0    Other_State      133.7
19642   5/1/2021     25_34  Other_Industry      0.0    Other_State      127.2

      Years_proexp Years_fieldexp Gender                 Race  \
0        5_7_years      5_7_years  Woman                White
1        2_4_years      2_4_years  Woman                White
2       8_10_years      5_7_years  Woman                White
3       8_10_years      5_7_years  Woman                White
4       8_10_years      2_4_years    Man                White
...            ...            ...    ...                  ...
19638  1_year_less    1_year_less    Man  Asian_AsianAmerican
19639    5_7_years      5_7_years    Man                White
19640  21_30_years    21_30_years  Woman                White
19641  21_30_years      5_7_years    Man                White
19642   8_10_years      2_4_years  Woman                White

       Edu_level_College_degree  Edu_level_High_School  \
0                             0                      0
1                             1                      0
2                             1                      0
3                             1                      0
4                             0                      0
...                         ...                    ...
19638                         1                      0
19639                         0                      0
19640                         0                      0
19641                         0                      0
19642                         0                      0

       Edu_level_Masters_degree  Edu_level_PhD  Edu_level_Professional_degree  \
0                             1              0                              0
1                             0              0                              0
2                             0              0                              0
3                             0              0                              0
4                             1              0                              0
...                         ...            ...                            ...
19638                         0              0                              0
19639                         0              1                              0
19640                         0              0                              0
19641                         1              0                              0
19642                         1              0                              0

       Edu_level_Some_college
0                           0
1                           0
2                           0
3                           0
4                           0
...                       ...
19638                       0
19639                       0
19640                       1
19641                       0
19642                       0

[19643 rows x 16 columns]

In [51]:
#Regression expression excluding High_School as the intercept
reg_exp = 'Salary ~ Edu_level_Some_college + Edu_level_College_degree + Edu_level_Masters_degree + Edu_level_PhD + Edu_level_Professional_degree'

In [52]:
#Building and training the model before printing the results
olsr_model = smf.ols(formula=reg_exp, data=salaryData_with_dummies)
olsr_model_results = olsr_model.fit()
print(olsr_model_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.036
Model:                            OLS   Adj. R-squared:                  0.036
Method:                 Least Squares   F-statistic:                     146.9
Date:                Mon, 21 Nov 2022   Prob (F-statistic):          1.24e-153
Time:                        22:10:05   Log-Likelihood:            -2.3585e+05
No. Observations:               19643   AIC:                         4.717e+05
Df Residuals:                   19637   BIC:                         4.718e+05
Df Model:                           5
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                      7.286e+04   2241.772     32.503      0.000    6.85e+04    7.73e+04
Edu_level_Some_college         1768.5243   2486.052      0.711      0.477   -3104.349    6641.397
Edu_level_College_degree       1.167e+04   2277.576      5.124      0.000    7206.392    1.61e+04
Edu_level_Masters_degree       1.541e+04   2295.145      6.713      0.000    1.09e+04    1.99e+04
Edu_level_PhD                  3.144e+04   2594.534     12.117      0.000    2.64e+04    3.65e+04
Edu_level_Professional_degree  3.964e+04   2631.159     15.064      0.000    3.45e+04    4.48e+04
==============================================================================
Omnibus:                     1876.511   Durbin-Watson:                   1.929
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2458.934
Skew:                           0.857   Prob(JB):                         0.00
Kurtosis:                       3.258   Cond. No.                         23.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [41]:
#Creating dummy variables for Gender
salaryData_with_dummies = pd.get_dummies(data=salaryData, columns=['Gender'])

In [42]:
print(salaryData_with_dummies)

            Date Age_group        Industry   Salary          State  Col_State  \
0      4/27/2021     25_34  Other_Industry  55000.0  Massachusetts      129.9
1      4/27/2021     25_34  Other_Industry  34000.0    Other_State       89.7
2      4/27/2021     25_34  Other_Industry  65000.0    Other_State       96.1
3      4/27/2021     25_34  Other_Industry  67000.0    Other_State       95.9
4      4/27/2021     25_34  Other_Industry  62000.0    Other_State      108.4
...          ...       ...             ...      ...            ...        ...
19638  4/28/2021     18_24  Computing_Tech      0.0     California      142.4
19639  4/28/2021     45_54  Other_Industry      0.0     California      142.4
19640  4/29/2021     45_54  Computing_Tech      0.0     California      142.4
19641  4/29/2021     35_44  Other_Industry      0.0    Other_State      133.7
19642   5/1/2021     25_34  Other_Industry      0.0    Other_State      127.2

      Years_proexp Years_fieldexp       Edu_level                 Race  \
0        5_7_years      5_7_years  Masters_degree                White
1        2_4_years      2_4_years  College_degree                White
2       8_10_years      5_7_years  College_degree                White
3       8_10_years      5_7_years  College_degree                White
4       8_10_years      2_4_years  Masters_degree                White
...            ...            ...             ...                  ...
19638  1_year_less    1_year_less  College_degree  Asian_AsianAmerican
19639    5_7_years      5_7_years             PhD                White
19640  21_30_years    21_30_years    Some_college                White
19641  21_30_years      5_7_years  Masters_degree                White
19642   8_10_years      2_4_years  Masters_degree                White

       Gender_Man  Gender_Non_binary  Gender_Other  Gender_Woman
0               0                  0             0             1
1               0                  0             0             1
2               0                  0             0             1
3               0                  0             0             1
4               1                  0             0             0
...           ...                ...           ...           ...
19638           1                  0             0             0
19639           1                  0             0             0
19640           0                  0             0             1
19641           1                  0             0             0
19642           0                  0             0             1

[19643 rows x 14 columns]

In [43]:
#Regression expression excluding Gender_Other as the intercept
reg_exp = 'Salary ~ Gender_Man + Gender_Woman + Gender_Non_binary'

In [44]:
#Building and training the model before printing the results
olsr_model = smf.ols(formula=reg_exp, data=salaryData_with_dummies)
olsr_model_results = olsr_model.fit()
print(olsr_model_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.039
Model:                            OLS   Adj. R-squared:                  0.039
Method:                 Least Squares   F-statistic:                     263.6
Date:                Mon, 21 Nov 2022   Prob (F-statistic):          9.34e-168
Time:                        21:29:01   Log-Likelihood:            -2.3582e+05
No. Observations:               19643   AIC:                         4.717e+05
Df Residuals:                   19639   BIC:                         4.717e+05
Df Model:                           3
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept          8.307e+04   3864.992     21.492      0.000    7.55e+04    9.06e+04
Gender_Man         2.145e+04   3929.799      5.459      0.000    1.37e+04    2.92e+04
Gender_Woman       1131.5282   3877.739      0.292      0.770   -6469.169    8732.225
Gender_Non_binary -1.333e+04   4223.439     -3.155      0.002   -2.16e+04   -5047.930
==============================================================================
Omnibus:                     1633.466   Durbin-Watson:                   1.947
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2069.918
Skew:                           0.788   Prob(JB):                         0.00
Kurtosis:                       3.218   Cond. No.                         36.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [45]:
#Creating dummy variables for Race
salaryData_with_dummies = pd.get_dummies(data=salaryData, columns=['Race'])

In [46]:
print(salaryData_with_dummies)

            Date Age_group        Industry   Salary          State  Col_State  \
0      4/27/2021     25_34  Other_Industry  55000.0  Massachusetts      129.9
1      4/27/2021     25_34  Other_Industry  34000.0    Other_State       89.7
2      4/27/2021     25_34  Other_Industry  65000.0    Other_State       96.1
3      4/27/2021     25_34  Other_Industry  67000.0    Other_State       95.9
4      4/27/2021     25_34  Other_Industry  62000.0    Other_State      108.4
...          ...       ...             ...      ...            ...        ...
19638  4/28/2021     18_24  Computing_Tech      0.0     California      142.4
19639  4/28/2021     45_54  Other_Industry      0.0     California      142.4
19640  4/29/2021     45_54  Computing_Tech      0.0     California      142.4
19641  4/29/2021     35_44  Other_Industry      0.0    Other_State      133.7
19642   5/1/2021     25_34  Other_Industry      0.0    Other_State      127.2

      Years_proexp Years_fieldexp       Edu_level Gender  \
0        5_7_years      5_7_years  Masters_degree  Woman
1        2_4_years      2_4_years  College_degree  Woman
2       8_10_years      5_7_years  College_degree  Woman
3       8_10_years      5_7_years  College_degree  Woman
4       8_10_years      2_4_years  Masters_degree    Man
...            ...            ...             ...    ...
19638  1_year_less    1_year_less  College_degree    Man
19639    5_7_years      5_7_years             PhD    Man
19640  21_30_years    21_30_years    Some_college  Woman
19641  21_30_years      5_7_years  Masters_degree    Man
19642   8_10_years      2_4_years  Masters_degree  Woman

       Race_Asian_AsianAmerican  Race_Black_AfricanAmerican  \
0                             0                           0
1                             0                           0
2                             0                           0
3                             0                           0
4                             0                           0
...                         ...                         ...
19638                         1                           0
19639                         0                           0
19640                         0                           0
19641                         0                           0
19642                         0                           0

       Race_Hispanic_Latino_Spanishorigin  Race_MiddleEastern_NorthernAfrican  \
0                                       0                                   0
1                                       0                                   0
2                                       0                                   0
3                                       0                                   0
4                                       0                                   0
...                                   ...                                 ...
19638                                   0                                   0
19639                                   0                                   0
19640                                   0                                   0
19641                                   0                                   0
19642                                   0                                   0

       Race_Mixed_Race  Race_NativeAmerican_AlaskaNative  Race_White
0                    0                                 0           1
1                    0                                 0           1
2                    0                                 0           1
3                    0                                 0           1
4                    0                                 0           1
...                ...                               ...         ...
19638                0                                 0           0
19639                0                                 0           1
19640                0                                 0           1
19641                0                                 0           1
19642                0                                 0           1

[19643 rows x 17 columns]

In [47]:
#Regression expression excluding Mixed_Race as the intercept
reg_exp = 'Salary ~ Race_Asian_AsianAmerican + Race_Black_AfricanAmerican + Race_Hispanic_Latino_Spanishorigin + Race_MiddleEastern_NorthernAfrican + Race_NativeAmerican_AlaskaNative + Race_White'

In [48]:
#Building and training the model before printing the results
olsr_model = smf.ols(formula=reg_exp, data=salaryData_with_dummies)
olsr_model_results = olsr_model.fit()
print(olsr_model_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Salary   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     24.64
Date:                Mon, 21 Nov 2022   Prob (F-statistic):           2.86e-29
Time:                        21:36:39   Log-Likelihood:            -2.3614e+05
No. Observations:               19643   AIC:                         4.723e+05
Df Residuals:                   19636   BIC:                         4.723e+05
Df Model:                           6
Covariance Type:            nonrobust
======================================================================================================
                                         coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                           8.485e+04   1304.375     65.048      0.000    8.23e+04    8.74e+04
Race_Asian_AsianAmerican            1.769e+04   1890.479      9.359      0.000     1.4e+04    2.14e+04
Race_Black_AfricanAmerican          3099.5940   2211.297      1.402      0.161   -1234.735    7433.923
Race_Hispanic_Latino_Spanishorigin   645.6372   2347.875      0.275      0.783   -3956.396    5247.671
Race_MiddleEastern_NorthernAfrican  2.182e+04   6575.169      3.319      0.001    8932.405    3.47e+04
Race_NativeAmerican_AlaskaNative   -4716.4569   7024.273     -0.671      0.502   -1.85e+04    9051.715
Race_White                          1459.7921   1340.780      1.089      0.276   -1168.251    4087.835
==============================================================================
Omnibus:                     1781.514   Durbin-Watson:                   1.933
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2307.730
Skew:                           0.834   Prob(JB):                         0.00
Kurtosis:                       3.194   Cond. No.                         33.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.